// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Eve_Market_Data.IDItemInfoJsonTypes;

namespace Eve_Market_Data
{

    public class IDItemInfo
    {

        [JsonProperty("totalCount_str")]
        public string TotalCountStr { get; set; }

        [JsonProperty("pageCount")]
        public int PageCount { get; set; }

        [JsonProperty("items")]
        public Item[] Items { get; set; }

        [JsonProperty("next")]
        public Next Next { get; set; }

        [JsonProperty("totalCount")]
        public int TotalCount { get; set; }

        [JsonProperty("pageCount_str")]
        public string PageCountStr { get; set; }
    }

}
