// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Eve_Market_Data.IDItemInfoJsonTypes;

namespace Eve_Market_Data.IDItemInfoJsonTypes
{

    public class Item
    {

        [JsonProperty("id_str")]
        public string IdStr { get; set; }

        [JsonProperty("href")]
        public string Href { get; set; }

        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }
    }

}
