// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Eve_Market_Data.ItemDetailJsonTypes;

namespace Eve_Market_Data.ItemDetailJsonTypes
{

    public class Attribute2
    {

        [JsonProperty("id_str")]
        public string IdStr { get; set; }

        [JsonProperty("href")]
        public string Href { get; set; }

        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }
    }

    public class Attribute
    {

        [JsonProperty("attribute")]
        public Attribute2 Attribute2 { get; set; }

        [JsonProperty("value")]
        public int Value { get; set; }
    }

    public class Dogma
    {

        [JsonProperty("attributes")]
        public Attribute[] Attributes { get; set; }
    }

}

namespace Eve_Market_Data
{

    public class ItemDetail
    {

        [JsonProperty("capacity")]
        public int Capacity { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("portionSize_str")]
        public string PortionSizeStr { get; set; }

        [JsonProperty("iconID")]
        public int IconID { get; set; }

        [JsonProperty("portionSize")]
        public int PortionSize { get; set; }

        [JsonProperty("iconID_str")]
        public string IconIDStr { get; set; }

        [JsonProperty("volume")]
        public int Volume { get; set; }

        [JsonProperty("dogma")]
        public Dogma Dogma { get; set; }

        [JsonProperty("radius")]
        public int Radius { get; set; }

        [JsonProperty("id_str")]
        public string IdStr { get; set; }

        [JsonProperty("published")]
        public bool Published { get; set; }

        [JsonProperty("mass")]
        public int Mass { get; set; }

        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }
    }

}
