// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Eve_Market_Data.IDItemInfoJsonTypes;

namespace Eve_Market_Data.IDItemInfoJsonTypes
{

    public class Next
    {

        [JsonProperty("href")]
        public string Href { get; set; }
    }

}
